[package]
name = "lintcheck-driver"
version = "0.0.1"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
