[crates]
# Top ~200 crates from crates.io
syn = { name = 'syn', version = '2.0.71' }
bitflags = { name = 'bitflags', version = '2.6.0' }
hashbrown = { name = 'hashbrown', version = '0.14.5' }
base64 = { name = 'base64', version = '0.22.1' }
regex-syntax = { name = 'regex-syntax', version = '0.8.4' }
proc-macro2 = { name = 'proc-macro2', version = '1.0.86' }
indexmap = { name = 'indexmap', version = '2.2.6' }
quote = { name = 'quote', version = '1.0.36' }
regex-automata = { name = 'regex-automata', version = '0.4.7' }
libc = { name = 'libc', version = '0.2.155' }
serde = { name = 'serde', version = '1.0.204' }
