[crates]
syn = { name = 'syn', version = '2.0.71' }
bitflags = { name = 'bitflags', version = '2.6.0' }
hashbrown = { name = 'hashbrown', version = '0.14.5' }
base64 = { name = 'base64', version = '0.22.1' }
regex-syntax = { name = 'regex-syntax', version = '0.8.4' }
proc-macro2 = { name = 'proc-macro2', version = '1.0.86' }
