[crates]
# Binaries projects
cargo = { version = "0.86.0", artifact = "bin" }
ripgrep = { version = "14.1.0", artifact = "bin" }
bat = { version = "0.25.0", artifact = "bin" }
fend = { version = "1.5.0", artifact = "bin" }
mdbook = { version = "0.4.40", artifact = "bin" }

# Bigger crates from ICE issues:
wasmi = "0.35.0"
wgpu = "0.20.1"
bytes = "1.6.1"
skrifa = "0.19.3"

# Random crates which are part of the default test set
puffin = "0.19.0"

# Top ~200 crates from crates.io
syn = "2.0.100"
bitflags = "2.6.0"
hashbrown = "0.14.5"
base64 = "0.22.1"
regex-syntax = "0.8.5"
proc-macro2 = "1.0.94"
indexmap = "2.9.0"
quote = "1.0.36"
regex-automata = "0.4.9"
libc = "0.2.155"
serde = "1.0.204"
itertools = "0.13.0"
heck = "0.5.0"
memchr = "2.7.4"
serde_derive = "1.0.204"
unicode-ident = "1.0.12"
autocfg = "1.3.0"
cfg-if = "1.0.0"
aho-corasick = "1.1.3"
getrandom = "0.2.15"
rand_core = "0.6.4"
serde_json = "1.0.120"
itoa = "1.0.11"
rand = "0.8.5"
ryu = "1.0.18"
once_cell = "1.21.3"
rustix = "0.38.34"
regex = "1.11.1"
log = "0.4.22"
parking_lot_core = "0.9.10"
cc = "1.1.5"
strsim = "0.11.1"
clap = "4.5.35"
parking_lot = "0.12.3"
smallvec = "2.0.0-alpha.6"
thiserror-impl = "1.0.63"
thiserror = "1.0.63"
linux-raw-sys = "0.6.4"
socket2 = "0.5.7"
idna = "1.0.2"
fastrand = "2.1.0"
either = "1.13.0"
num-traits = "0.2.19"
rand_chacha = "0.3.1"
lazy_static = "1.5.0"
semver = "1.0.23"
lock_api = "0.4.12"
scopeguard = "1.2.0"
ahash = "0.8.11"
anyhow = "1.0.86"
rustls = "0.23.11"
http = "1.1.0"
toml_edit = "0.22.24"
pin-project-lite = "0.2.14"
spin = "0.9.8"
miniz_oxide = "0.7.4"
memoffset = "0.9.1"
digest = "0.11.0-pre.8"
version_check = "0.9.4"
clap_lex = "0.7.4"
crossbeam-utils = "0.8.20"
toml = "0.8.20"
block-buffer = "0.10.4"
time = "0.3.36"
hyper = "1.4.1"
url = "2.5.2"
percent-encoding = "2.3.1"
tokio = "1.38.1"
errno = "0.3.9"
uuid = "1.10.0"
unicode-normalization = "0.1.23"
ppv-lite86 = "0.2.17"
futures-core = "0.3.31"
http-body = "1.0.1"
tinyvec = "1.8.0"
futures-util = "0.3.31"
futures-task = "0.3.31"
sha2 = "0.11.0-pre.3"
ring = "0.17.8"
slab = "0.4.9"
chrono = "0.4.38"
futures-sink = "0.3.31"
futures-channel = "0.3.31"
num_cpus = "1.16.0"
untrusted = "0.9.0"
tinyvec_macros = "0.1.1"
mio = "1.0.0"
byteorder = "1.5.0"
form_urlencoded = "1.2.1"
unicode-bidi = "0.3.15"
futures-io = "0.3.31"
tokio-util = "0.7.11"
rustls-pemfile = "2.1.2"
generic-array = "1.1.0"
tracing = "0.1.40"
equivalent = "1.0.1"
tracing-core = "0.1.32"
pin-utils = "0.1.0"
tempfile = "3.10.1"
h2 = "0.4.5"
futures = "0.3.31"
typenum = "1.17.0"
winnow = "0.6.18"
cpufeatures = "0.2.12"
nix = "0.29.0"
fnv = "1.0.7"
# As of 2025-04-01, one dependency doesn't build because of cmake version discrepancy
# tokio-rustls = "0.26.0"
iana-time-zone = "0.1.60"
rustls-webpki = "0.102.5"
crc32fast = "1.4.2"
adler = "1.0.2"
pkg-config = "0.3.30"
redox_syscall = "0.5.3"
nom = "8.0.0-alpha2"
rustc_version = "0.4.0"
futures-macro = "0.3.31"
clap_derive = "4.5.8"
futures-executor = "0.3.31"
event-listener = "5.3.1"
num-integer = "0.1.46"
time-macros = "0.2.18"
flate2 = "1.1.1"
tokio-macros = "2.3.0"
strum_macros = "0.26.4"
tracing-attributes = "0.1.27"
async-trait = "0.1.81"
crypto-common = "0.1.6"
unicode-width = "0.1.13"
anstyle = "1.0.10"
object = "0.36.1"
gimli = "0.31.0"
crossbeam-epoch = "0.9.18"
thread_local = "1.1.8"
strum = "0.26.3"
darling_core = "0.20.10"
darling_macro = "0.20.10"
minimal-lexical = "0.2.1"
clap_builder = "4.5.35"
time-core = "0.1.2"
httparse = "1.9.4"
signal-hook-registry = "1.4.2"
hex = "0.4.3"
crossbeam-deque = "0.8.5"
zerocopy = "0.7.35"
rustversion = "1.0.17"
env_logger = "0.11.3"
webpki-roots = "0.26.3"
rustc-demangle = "0.1.24"
mime = "0.3.17"
termcolor = "1.4.1"
subtle = "2.6.1"
walkdir = "2.5.0"
hermit-abi = "0.4.0"
pin-project = "1.1.5"
pin-project-internal = "1.1.5"
try-lock = "0.2.5"
tracing-log = "0.2.0"
httpdate = "1.0.3"
anstream = "0.6.18"
crossbeam-channel = "0.5.13"
reqwest = "0.12.5"
want = "0.3.1"
paste = "1.0.15"
anstyle-parse = "0.2.4"
toml_datetime = "0.6.8"
anstyle-query = "1.1.0"
addr2line = "0.24.0"
glob = "0.3.1"
num-bigint = "0.4.6"
backtrace = "0.3.73"
wasi = "0.13.1+wasi-0.2.0"
tower-service = "0.3.2"
sync_wrapper = "1.0.1"
libloading = "0.8.4"
rayon = "1.10.0"
colorchoice = "1.0.1"
encoding_rs = "0.8.35"
deranged = "0.3.11"
zeroize = "1.8.1"
utf8parse = "0.2.2"
tracing-subscriber = "0.3.18"
hyper-rustls = "0.27.2"
hmac = "0.13.0-pre.3"
rayon-core = "1.12.1"
same-file = "1.0.6"
prost = "0.13.1"
sharded-slab = "0.1.7"
textwrap = "0.16.1"
bumpalo = "3.16.0"
arrayvec = "0.7.4"
