# If you want to check a local project it"s usually easier to use:
# ```
# cargo dev lint <path>
# ```
#
# For testing you can also add sources to git and local repos like this:
# ```
# crate = {name = "crate", git_url = "https://github.com/name/repo.git", git_hash = "coo1cafe"}
# crate = {name = "crate", path = "/path/to/project"}
# ```

[crates]

# Some binaries
cargo = { version = "0.80.0", artifact = "bin" }
ripgrep = { version = "14.1.0", artifact = "bin" }
mdbook = { version = "0.4.40", artifact = "bin" }

# Common libraries
proc-macro2 = "1.0.86"
rayon = "1.10.0"
serde = "1.0.204"
bitflags = "2.6.0"
log = "0.4.22"
quote = "1.0.36"
rand = "0.8.5"
rand_core = "0.6.4"
regex = "1.10.5"
syn = "2.0.71"
anyhow = "1.0.86"
async-trait = "0.1.81"
cxx = "1.0.124"
ryu = "1.0.18"
thiserror = "1.0.63"
# serde_yaml = "0.9.33"
puffin = "0.19.0"
bumpalo = "3.16.0"
wasmi = "0.35.0"
base64 = "0.22.1"
once_cell = "1.19.0"
tokio = "1.38.1"

[recursive]
ignore = ["git2"]
