name: Clippy Test (bors)

on:
  push:

env:
  RUST_BACKTRACE: 1
  CARGO_TARGET_DIR: '${{ github.workspace }}/target'
  NO_FMT_TEST: 1
  CARGO_INCREMENTAL: 0

defaults:
  run:
    shell: bash

jobs:
  base:
    strategy:
      matrix:
        include:
        - os: macos-latest
          host: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    # NOTE: If you modify this job, make sure you copy the changes to clippy.yml
    steps:
    # Setup
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        rustup set default-host ${{ matrix.host }}
        rustup show active-toolchain

    # Run
    - name: Link rustc dylib (MacOS)
      if: runner.os == 'macOS'
      run: |
        SYSROOT=$(rustc --print sysroot)
        sudo mkdir -p /usr/local/lib
        sudo find "${SYSROOT}/lib" -maxdepth 1 -name '*dylib' -exec ln -s {} /usr/local/lib \;

    - name: Build
      run: cargo build --tests --features deny-warnings,internal

    - name: Test 1
      run: cargo test --features deny-warnings,internal -- --skip dogfood
    - name: Test 2
      run: cargo test --features deny-warnings,internal -- --skip dogfood
    - name: Test 3
      run: cargo test --features deny-warnings,internal -- --skip dogfood
    - name: Test 4
      run: cargo test --features deny-warnings,internal -- --skip dogfood
    - name: Test 5
      run: cargo test --features deny-warnings,internal -- --skip dogfood
