name: Lintcheck

on: pull_request

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  base:
    runs-on: ubuntu-latest

    outputs:
      key: ${{ steps.key.outputs.key }}

    steps:
    - name: Checkout merge base
      uses: actions/checkout@v3
      with:
        # ref: ${{ github.event.pull_request.base.sha }}
        fetch-depth: 0

    - run: echo '${{ toJSON(github) }}'
    - run: git log -1 ${{ github.event.pull_request.base.sha }} || true
    - run: git log -1 ${{ github.sha }} || true
    - run: git log -1

    - name: Checkout current lintcheck
      run: |
        rm -rf lintcheck
        git checkout ${{ github.sha }} -- lintcheck

    - name: Create cache key
      id: key
      run: echo "key=lintcheck-base-${{ hashfiles('lintcheck/**') }}-${{ github.event.pull_request.base.sha }}" >> "$GITHUB_OUTPUT"

    - name: Cache results
      id: cache
      uses: actions/cache@v3
      with:
        path: lintcheck-logs/base.json
        key: ${{ steps.key.outputs.key }}

    - name: Run lintcheck
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo lintcheck --json

    - name: Rename JSON file
      if: steps.cache.outputs.cache-hit != 'true'
      run: mv lintcheck-logs/lintcheck_crates_logs.json lintcheck-logs/base.json

  pr:
    runs-on: ubuntu-latest

    outputs:
      key: ${{ steps.key.outputs.key }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Create cache key
      id: key
      run: echo "key=lintcheck-pr-${{ github.ref }}" >> "$GITHUB_OUTPUT"

    - name: Cache results
      id: cache
      uses: actions/cache@v3
      with:
        path: lintcheck-logs/base.json
        key: ${{ steps.key.outputs.key }}

    - name: Run lintcheck
      if: steps.cache.outputs.cache-hit != 'true'
      run: cargo lintcheck --json

    - name: Rename JSON file
      if: steps.cache.outputs.cache-hit != 'true'
      run: mv lintcheck-logs/lintcheck_crates_logs.json lintcheck-logs/pr.json

  diff:
    runs-on: ubuntu-latest

    needs: [base, pr]

    steps:
    - name: Restore base JSON
      uses: actions/cache/restore@v3
      with:
        key: ${{ needs.base.outputs.key }}
        fail-on-cache-miss: true

    - name: Restore PR JSON
      uses: actions/cache/restore@v3
      with:
        key: ${{ needs.pr.outputs.key }}
        fail-on-cache-miss: true

    - name: Diff results
      run: cargo lintcheck diff lintcheck-logs/base.json lintcheck-logs/pr.json
